version: '3.8'

services:
  php-app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - variables.env

volumes:
  mysql:
